### PR TITLE
Improve schematics

### PR DESCRIPTION
**Pull request by hanshuebner**
- Add address bus
- Add power nets
- Move decoupling caps out of sight

Not yet done:

 - Data bus
 - GPIO bus

### CODE REVIEW

**Comment by hanshuebner** [comment]
Thanks for the review, Terence.  I've corrected the CE line of the EEPROM now.  I've also connected A13 of the EEPROM to GND as it was originally floating.  It may make sense to connect it to the U7 latch instead like the other high address bits.  There might be a use for some more EEPROM space in the future.

I'm not too happy with the ERC output either.  The warnings regarding the Pi's power pins don't bother me too much, but there are some messages around the address bus near the slot connector which I have not figured out to remove yet.  I generally get rid of all ERC messages as they're very helpful during development.

**Comment by tjboldt** [comment]
I'll clean up the PCB warnings and errors after your merge. Those didn't show up in KiCAD 5 but KiCAD 6 is more picky (in a good way). As for A13, there isn't an A13 on the AT28C64B. The schematic shows a larger capacity EPROM as I couldn't find the right 28 series chip in the default library. I should have created a new component but was too excited about getting going on writing firmware and software.

AT28C64B

**Comment by hanshuebner** [comment]
> I should have created a new component but was too excited about getting going on writing firmware and software.

I can totally relate!  Let me know when you're done with whatever changes you want to make on the schematic, then I'll add the GPIO bus - That will really be helpful in finding out how things are connected, in particular on a paper printout.

One of the nice advantages of KiCAD 6 is that components embedded in the schematic can easily be edited.  That is how I added the signal names to the slot connector, and it should be easy to remove A13 from the AT28C64B, too.

**Comment by tjboldt** [comment]
Thanks Hans. I was only making temporary changes to see what I’d need to do to fix the warnings and errors in the PCB. It looks like only an hour or two of work but I will wait until after your schematic changes are done.

**Comment by hanshuebner** [comment]
> Thanks Hans. I was only making temporary changes to see what I’d need to do to fix the warnings and errors in the PCB. It looks like only an hour or two of work but I will wait until after your schematic changes are done.

Alright - I'll probably get to it tomorrow morning.  Will ping you on this PR.

**Comment by hanshuebner** [comment]
I've fixed the AT28C64B component (Added WE pin, remove unused address pins) and added the GPIO bus.  I'm done for now.

**Review by tjboldt — APPROVED** [review]
Looks good. Thanks for all your help.

**Pull request merged**
